tenant:
  name: GUID
  user:
    name: USERNAME

replicaCount: 1

image:
  repository: quay.io/eformat/multimodal-chatbot
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

route:
  enabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

config:
  secretName: multimodal-chatbot
  mountPath: /opt/app-rot/src/config
  configFile: /opt/app-rot/src/config/config.json
  systemTemplate: >-
    You are a helpful, knowledgeable, and friendly assistant having a conversation
    with a human. Respond clearly, concisely, and accurately to user questions and
    requests. Adapt your tone to match the user's style—professional, casual, or
    otherwise. If clarification is needed, ask thoughtful follow-up questions. When
    appropriate, offer examples, summaries, or step-by-step guidance. Do not make up
    information; if you are unsure, say so. Be polite, nonjudgmental, and always aim
    to provide useful, easy-to-understand responses. Give your answer in {language}
    only, but don't translate any code. If your answer is not in English, don't give
    the English translation. Your answers should not include any harmful, unethical,
    racist, sexist, toxic, dangerous, or illegal content.
  translateSystemTemplate: >-
    Translate the following text to English. Translate the text as concisely as
    possible. Don't add any comment or information. If the text is already in
    English, don't modify it, just copy it without any other mention.
