---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    opendatahub.io/dashboard: "true"
    kueue.openshift.io/managed: "true"
  annotations:
    openshift.io/description: 'Chat'
    openshift.io/display-name: chat
  name: chat
spec: {}

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    opendatahub.io/dashboard: "true"
    kueue.openshift.io/managed: "true"
  annotations:
    openshift.io/description: 'Red Claw'
    openshift.io/display-name: claw
  name: claw
spec: {}
