apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.config.secretName }}
  labels:
    app: multimodal-chatbot
type: Opaque
stringData:
  config.json: |-
    {
        "system_template": {{ .Values.config.systemTemplate | quote }},
        "translate_system_template": {{ .Values.config.translateSystemTemplate | quote }}
    }
